[package]
name = "gtkrs"
version = "0.2.0"
authors = ["shujinarazaki <shujinarazaki@protonmail.com>"]
edition = "2021"

[dependencies]
gtk = { version = "^0.4", package = "gtk4", features = ["v4_6"] }
